"""Assemble the Phase 2 sim attack report (structured + markdown).

The report is a deliverable (SIM_REPORT.md). It is generated from the sim,
never hand-edited, so it cannot drift from what the code actually proves.
"""
from __future__ import annotations

from chronarch_spec.constants import GYM_CASE_CATALOG

from .attacks import run_all_attacks
from .catalog import catalog_summary, run_gym_catalog
from .world import SimWorld


def build_report(world_factory=SimWorld) -> dict:
    fixture = world_factory()
    fixture_facts = {
        "nodes": len(fixture.node_ids),
        "all_boot_ok": all(n["report"]["boot_ok"] for n in fixture.nodes.values()),
        "ring0_hash": fixture.ring0_hash,
        "all_agree_on_ring0": fixture.all_nodes_agree_on_ring0(),
        "all_chains_verify": fixture.all_chains_verify(),
        "council_seats": len(fixture.seats),
    }
    catalog_rows = run_gym_catalog(fixture)
    summary = catalog_summary(catalog_rows)
    attacks = [o.as_dict() for o in run_all_attacks(world_factory)]
    return {
        "fixture": fixture_facts,
        "catalog": summary,
        "attacks": attacks,
        "all_defenses_held": all(a["held"] for a in attacks) and summary["all_pass"],
    }


def render_markdown(report: dict) -> str:
    f = report["fixture"]
    lines = [
        "# Phase 2 — Sim Attack Report",
        "",
        "Generated by `chronarch-sim` against a Chronarch-only fixture (G12). "
        "This file is produced from the sim, not hand-written — regenerate with "
        "`python -m chronarch_sim.report`.",
        "",
        "> Tampering is detectable, expensive, incomplete, and metabolized into a scar.",
        "",
        "## Fixture",
        "",
        f"- Nodes booted: **{f['nodes']}**, all boot-ok: **{f['all_boot_ok']}**",
        f"- Council seats (bonded stewards): **{f['council_seats']}**",
        f"- Every node agrees on Ring 0: **{f['all_agree_on_ring0']}** "
        f"(`{f['ring0_hash'][:16]}…`)",
        f"- Every node chain verifies: **{f['all_chains_verify']}**",
        "",
        "## The seven Phase-2 attacks",
        "",
        "| Attack | Must | Held | Observed |",
        "|---|---|:--:|---|",
    ]
    for a in report["attacks"]:
        mark = "✅" if a["held"] else "❌"
        lines.append(
            f"| **{a['title']}** ({', '.join(a['law_refs'])}) | {a['must']} | "
            f"{mark} | {a['observed']} |"
        )
    lines += [
        "",
        "## Immune Gym catalog across the fixture",
        "",
        f"All {report['catalog']['cases_run']} cases "
        f"({len(GYM_CASE_CATALOG)} attacks × {f['nodes']} nodes) — "
        f"every-node pass: **{report['catalog']['all_pass']}**.",
        "",
        "| Gym attack | Nodes detecting |",
        "|---|:--:|",
    ]
    for attack, e in report["catalog"]["by_attack"].items():
        lines.append(f"| `{attack}` | {e['detected']}/{e['total']} |")
    lines += [
        "",
        "## Verdict",
        "",
        f"**All defenses held: {report['all_defenses_held']}**",
        "",
        "No sim test proved a hole in the frozen kernel, admission, or Council. "
        "Any future red row here is a real defect, not a drill.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:  # python -m chronarch_sim.report
    import pathlib

    report = build_report()
    text = render_markdown(report)
    out = pathlib.Path(__file__).resolve().parents[4] / "SIM_REPORT.md"
    out.write_text(text)
    print(f"wrote {out} — all_defenses_held={report['all_defenses_held']}")


if __name__ == "__main__":
    main()
